const translations = {
  en: {
    title: "The reveal 🤞🏼",
    switchToQWERTY: "Switch to QWERTY",
    switchToAZERTY: "Switch to AZERTY",
    popup1title: "Propably Not !",
    popup1subTitle: "Wanna create your own version ?",
    popup2Title: "Title :",
    popup2TitlePh: "The reveal 🤞🏼",
    popup2Name: "Name :",
    popup2Success: "On success :",
    popup2SuccessPh: "🥰 Can't wait to meet ",
    popup2Fail: "On fail :",
    popup2FailPh: "Oops ! Seems like you'll have to wait 😋",
    popup2Anyway: "Give name anyway ?",
    popup2AnywayPh: "Just kiddin', it'll be "
  },
  fr: {
    title: "La révélation 🤞🏼",
    switchToQWERTY: "Passer en QWERTY",
    switchToAZERTY: "Passer en AZERTY",
    popup1title: "Sûrement pas !",
    popup1subTitle: "Voulez-vous créer votre version ?",
    popup2Title: "Titre :",
    popup2TitlePh: "La révélation 🤞🏼",
    popup2Name: "Prénom :",
    popup2Success: "En cas de succès :",
    popup2SuccessPh: "🥰 Trop hâte de rencontrer ",
    popup2Fail: "En cas d'échec :",
    popup2FailPh: "Oops ! Il semblerait que tu doives attendre 😋",
    popup2Anyway: "Révéler quand même ?",
    popup2AnywayPh: "Non je rigole, ça sera "
  },
  es: {
    title: "La revelación 🤞🏼",
    switchToQWERTY: "Cambiar a QWERTY",
    switchToAZERTY: "Cambiar a AZERTY",
    popup1title: "¡Probablemente no!",
    popup1subTitle: "¿Quieres crear tu propia versión?",
    popup2Title: "Título:",
    popup2TitlePh: "La revelación 🤞🏼",
    popup2Name: "Nombre:",
    popup2Success: "Si aciertas:",
    popup2SuccessPh: "🥰 No puedo esperar a conocer a ",
    popup2Fail: "Si fallas:",
    popup2FailPh: "¡Ups! Parece que tendrás que esperar 😋",
    popup2Anyway: "¿Revelar el nombre igual?",
    popup2AnywayPh: "Es broma, será "
  },
  de: {
    title: "Die Enthüllung 🤞🏼",
    switchToQWERTY: "Zu QWERTY wechseln",
    switchToAZERTY: "Zu AZERTY wechseln",
    popup1title: "Wahrscheinlich nicht!",
    popup1subTitle: "Möchtest du deine eigene Version erstellen?",
    popup2Title: "Titel:",
    popup2TitlePh: "Die Enthüllung 🤞🏼",
    popup2Name: "Name:",
    popup2Success: "Bei Erfolg:",
    popup2SuccessPh: "🥰 Kann es kaum erwarten, ",
    popup2Fail: "Bei Misserfolg:",
    popup2FailPh: "Oops! Sieht so aus, als müsstest du noch warten 😋",
    popup2Anyway: "Name trotzdem zeigen?",
    popup2AnywayPh: "Nur Spaß, es wird "
  },
  it: {
    title: "La rivelazione 🤞🏼",
    switchToQWERTY: "Passa a QWERTY",
    switchToAZERTY: "Passa a AZERTY",
    popup1title: "Probabilmente no!",
    popup1subTitle: "Vuoi creare la tua versione?",
    popup2Title: "Titolo:",
    popup2TitlePh: "La rivelazione 🤞🏼",
    popup2Name: "Nome:",
    popup2Success: "Se indovini:",
    popup2SuccessPh: "🥰 Non vedo l'ora di incontrare ",
    popup2Fail: "Se sbagli:",
    popup2FailPh: "Oops! Sembra che dovrai aspettare 😋",
    popup2Anyway: "Rivelare comunque?",
    popup2AnywayPh: "Scherzo, sarà "
  },
  pt: {
    title: "A revelação 🤞🏼",
    switchToQWERTY: "Mudar para QWERTY",
    switchToAZERTY: "Mudar para AZERTY",
    popup1title: "Provavelmente não!",
    popup1subTitle: "Quer criar sua própria versão?",
    popup2Title: "Título:",
    popup2TitlePh: "A revelação 🤞🏼",
    popup2Name: "Nome:",
    popup2Success: "Se acertar:",
    popup2SuccessPh: "🥰 Mal posso esperar para conhecer ",
    popup2Fail: "Se errar:",
    popup2FailPh: "Oops! Parece que vai ter que esperar 😋",
    popup2Anyway: "Revelar mesmo assim?",
    popup2AnywayPh: "Tô brincando, será "
  },
  nl: {
    title: "De onthulling 🤞🏼",
    switchToQWERTY: "Overschakelen naar QWERTY",
    switchToAZERTY: "Overschakelen naar AZERTY",
    popup1title: "Waarschijnlijk niet!",
    popup1subTitle: "Wil je je eigen versie maken?",
    popup2Title: "Titel:",
    popup2TitlePh: "De onthulling 🤞🏼",
    popup2Name: "Naam:",
    popup2Success: "Bij succes:",
    popup2SuccessPh: "🥰 Kan niet wachten om ",
    popup2Fail: "Bij mislukking:",
    popup2FailPh: "Oeps! Je zal nog even moeten wachten 😋",
    popup2Anyway: "Toch naam tonen?",
    popup2AnywayPh: "Grapje, het wordt "
  }
};