const translations = {
  en: {
    title: "Help us decide !",
    makeChoice: "Make your choice !",
    round: "Round",
    game: "Game",
    over: "over",
    finalChoice: "🏆 Final choice :",
    atLeastTwo: "You must at least type two names",
    titlePopup1: "Title :",
    titlePopup1Ph: "Help us decide !",
    linkForResult: "Keep this link to see the results",
    name: "Name",
    every30Sec: "Every 30 seconds",
    autoRefresh: "Refresh automatically"
  },
  fr: {
    title: "Aide nous à choisir !",
    makeChoice: "Fais ton choix !",
    round: "Tour",
    game: "Match",
    over: "sur",
    finalChoice: "🏆 Choix final :",
    atLeastTwo: "Vous devez entrer au moins deux prénoms",
    titlePopup1: "Titre :",
    titlePopup1Ph: "Aide nous à choisir !",
    linkForResult: "Gardez ce lien pour voir les résultats",
    name: "Prénom",
    every30Sec: "Toutes les 30 secondes",
    autoRefresh: "Rafraîchir automatiquement"
  },
  es: {
    title: "¡Ayúdanos a decidir!",
    makeChoice: "¡Haz tu elección!",
    round: "Ronda",
    game: "Partido",
    over: "de",
    finalChoice: "🏆 Elección final:",
    atLeastTwo: "Debes escribir al menos dos nombres",
    titlePopup1: "Título:",
    titlePopup1Ph: "¡Ayúdanos a decidir!",
    linkForResult: "Guarda este enlace para ver los resultados",
    name: "Nombre",
    every30Sec: "Cada 30 segundos",
    autoRefresh: "Actualizar automáticamente"
  },
  de: {
    title: "Hilf uns bei der Entscheidung!",
    makeChoice: "Triff deine Wahl!",
    round: "Runde",
    game: "Spiel",
    over: "von",
    finalChoice: "🏆 Endgültige Wahl:",
    atLeastTwo: "Du musst mindestens zwei Namen eingeben",
    titlePopup1: "Titel:",
    titlePopup1Ph: "Hilf uns bei der Entscheidung!",
    linkForResult: "Behalte diesen Link, um die Ergebnisse zu sehen",
    name: "Name",
    every30Sec: "Alle 30 Sekunden",
    autoRefresh: "Automatisch aktualisieren"
  },
  it: {
    title: "Aiutaci a decidere!",
    makeChoice: "Fai la tua scelta!",
    round: "Turno",
    game: "Partita",
    over: "su",
    finalChoice: "🏆 Scelta finale:",
    atLeastTwo: "Devi inserire almeno due nomi",
    titlePopup1: "Titolo:",
    titlePopup1Ph: "Aiutaci a decidere!",
    linkForResult: "Conserva questo link per vedere i risultati",
    name: "Nome",
    every30Sec: "Ogni 30 secondi",
    autoRefresh: "Aggiorna automaticamente"
  },
  pt: {
    title: "Ajude-nos a decidir!",
    makeChoice: "Faça sua escolha!",
    round: "Rodada",
    game: "Jogo",
    over: "de",
    finalChoice: "🏆 Escolha final:",
    atLeastTwo: "Você deve digitar pelo menos dois nomes",
    titlePopup1: "Título:",
    titlePopup1Ph: "Ajude-nos a decidir!",
    linkForResult: "Guarde este link para ver os resultados",
    name: "Nome",
    every30Sec: "A cada 30 segundos",
    autoRefresh: "Atualizar automaticamente"
  },
  nl: {
    title: "Help ons kiezen!",
    makeChoice: "Maak je keuze!",
    round: "Ronde",
    game: "Spel",
    over: "van",
    finalChoice: "🏆 Finale keuze:",
    atLeastTwo: "Je moet minstens twee namen invoeren",
    titlePopup1: "Titel:",
    titlePopup1Ph: "Help ons kiezen!",
    linkForResult: "Bewaar deze link om de resultaten te bekijken",
    name: "Naam",
    every30Sec: "Elke 30 seconden",
    autoRefresh: "Automatisch verversen"
  }
};
