const translations = {
  en: {
    title: "The reveal 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Can't find out! You have to create a new roulette first",
    createNew: "New roulette",

    popup1Title: "Title :",
    popup1TitlePh: "The reveal 🎰",
    popup1Gender: "Gender :",
    popup1GenderBoy: "Boy",
    popup1GenderGirl: "Girl",
    popup1Symbols: "Symbols :",
    popup1Success: "On success :",
    popup1SuccessPhBoy: "It's a boy 🎉",
    popup1SuccessPhGirl: "It's a girl 🎉",
    popup1Fail: "On fail :",
    popup1FailPh: "Oops! Try again... 🎲"
  },
  fr: {
    title: "La révélation 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Aucune idée! Crée une nouvelle machine avant",
    createNew: "Nouvelle machine",

    popup1Title: "Titre :",
    popup1TitlePh: "La révélation 🎰",
    popup1Gender: "Sexe :",
    popup1GenderBoy: "Garçon",
    popup1GenderGirl: "Fille",
    popup1Symbols: "Symboles :",
    popup1Success: "En cas de succès :",
    popup1SuccessPhBoy: "C'est un garçon 🎉",
    popup1SuccessPhGirl: "C'est une fille 🎉",
    popup1Fail: "En cas d'échec :",
    popup1FailPh: "Presque! Essaie à nouveau... 🎲"
  },
  es: {
    title: "¡La revelación! 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "¡No se puede saber! Primero debes crear una nueva ruleta",
    createNew: "Nueva ruleta",

    popup1Title: "Título:",
    popup1TitlePh: "¡La revelación! 🎰",
    popup1Gender: "Género:",
    popup1GenderBoy: "Niño",
    popup1GenderGirl: "Niña",
    popup1Symbols: "Símbolos:",
    popup1Success: "Si aciertas:",
    popup1SuccessPhBoy: "¡Es un niño! 🎉",
    popup1SuccessPhGirl: "¡Es una niña! 🎉",
    popup1Fail: "Si fallas:",
    popup1FailPh: "¡Uy! Intenta de nuevo... 🎲"
  },
  de: {
    title: "Die Enthüllung 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Unbekannt! Erstelle zuerst ein neues Roulette",
    createNew: "Neues Roulette",

    popup1Title: "Titel:",
    popup1TitlePh: "Die Enthüllung 🎰",
    popup1Gender: "Geschlecht:",
    popup1GenderBoy: "Junge",
    popup1GenderGirl: "Mädchen",
    popup1Symbols: "Symbole:",
    popup1Success: "Bei Erfolg:",
    popup1SuccessPhBoy: "Es ist ein Junge! 🎉",
    popup1SuccessPhGirl: "Es ist ein Mädchen! 🎉",
    popup1Fail: "Bei Misserfolg:",
    popup1FailPh: "Hoppla! Versuch’s noch mal... 🎲"
  },
  it: {
    title: "La rivelazione 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Non si può sapere! Crea prima una nuova roulette",
    createNew: "Nuova roulette",

    popup1Title: "Titolo:",
    popup1TitlePh: "La rivelazione 🎰",
    popup1Gender: "Genere:",
    popup1GenderBoy: "Maschio",
    popup1GenderGirl: "Femmina",
    popup1Symbols: "Simboli:",
    popup1Success: "In caso di successo:",
    popup1SuccessPhBoy: "È un maschietto! 🎉",
    popup1SuccessPhGirl: "È una femminuccia! 🎉",
    popup1Fail: "In caso di errore:",
    popup1FailPh: "Ops! Riprova... 🎲"
  },
  pt: {
    title: "A revelação 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Não dá para saber! Primeiro crie uma nova roleta",
    createNew: "Nova roleta",

    popup1Title: "Título:",
    popup1TitlePh: "A revelação 🎰",
    popup1Gender: "Gênero:",
    popup1GenderBoy: "Menino",
    popup1GenderGirl: "Menina",
    popup1Symbols: "Símbolos:",
    popup1Success: "Se acertar:",
    popup1SuccessPhBoy: "É um menino! 🎉",
    popup1SuccessPhGirl: "É uma menina! 🎉",
    popup1Fail: "Se errar:",
    popup1FailPh: "Ops! Tente de novo... 🎲"
  },
  nl: {
    title: "De onthulling 🎰",
    genderBoySymbol: "♂️",
    genderGirlSymbol: "♀️",
    createFirst: "Geen idee! Maak eerst een nieuw roulettewiel",
    createNew: "Nieuwe roulette",

    popup1Title: "Titel:",
    popup1TitlePh: "De onthulling 🎰",
    popup1Gender: "Geslacht:",
    popup1GenderBoy: "Jongen",
    popup1GenderGirl: "Meisje",
    popup1Symbols: "Symbolen:",
    popup1Success: "Bij succes:",
    popup1SuccessPhBoy: "Het is een jongen! 🎉",
    popup1SuccessPhGirl: "Het is een meisje! 🎉",
    popup1Fail: "Bij mislukking:",
    popup1FailPh: "Oeps! Probeer opnieuw... 🎲"
  }
};
